config/routes.rb
StaffManagement::Application.routes.draw do
  
  get "home/index"

  get "all/index"
devise_for :users

  resources :departments do 
      resources :staffs
  end
  match "all" => "all#index"
  match "home" => "home#index"

  root :to => 'home#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name
  has_many :staffs, :dependent =>  :destroy
  validates_presence_of :name
  validates_uniqueness_of :name
  scope :order_name, order("name")
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :department
  attr_accessible :age, :dob, :first_name, :last_name, :role, :salary, :sex, :department_id, :address
  validates_presence_of :age, :dob, :first_name, :last_name, :role, :salary, :sex, :department_id
 scope :order_firstname , order("first_name")


 def self.search(search)
 	if search 
 		find(:all, conditions:['first_name || last_name iLIKE ?', "%#{search}%"])
 	else
 		find(:all)
 	end
 end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/all_controller.rb
class AllController < ApplicationController
	before_filter :authenticate_user!
  def index
  	@staffs=Staff.order_firstname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :admin?
  protect_from_forgery
  def after_sign_in_path_for(user)
  	departments_path


 end

def admin?
false
redirect_to departments_path
end


end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.json
  before_filter :authenticate_user!
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # GET /staffs
  # GET /staffs.json
  before_filter :get_department
  def get_department
@department = Department.find(params[:department_id])

  end
  def index

    @staffs = @department.staffs.order_firstname.search(params[:search])
    if @staffs.class == Array
      @staffs = Kaminari.paginate_array(@staffs).page(params[:page]).per(7)
    else
        @staffs = @staffs.page(params[:page]).per(7)
    end



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staffs }
    end
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    @staff = @department.staffs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/new
  # GET /staffs/new.json
  def new
    @staff = @department.staffs.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/1/edit
  def edit
    @staff = @department.staffs.find(params[:id])
  end

  # POST /staffs
  # POST /staffs.json
def create
    @staff = @department.staffs.new(params[:staff])

    respond_to do |format|
      if @staff.save
        format.html { redirect_to ([@department, @staff]), notice: 'Staff was successfully created.' }
        format.json { render json: @staff, status: :created, location: @staff }
      else
        format.html { render action: "new" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /staffs/1
  # PUT /staffs/1.json
  def update
    @staff = @department.staffs.find(params[:id])

    respond_to do |format|
      if @staff.update_attributes(params[:staff])
        format.html { redirect_to [@department,@staff], notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff = @department.staffs.find(params[:id])
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to department_staffs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/all/index.html.erb
<%= render "layouts/navigation"%>
<div class="container">
<h3>Listing all staffs</h3>

<table class="table">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Role</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Dob</th>
    <th>Department</th>
  </tr>

<% @staffs.each do |staff| %>
  <tr>
    <td><%= staff.first_name %></td>
    <td><%= staff.last_name %></td>
    <td><%= staff.role %></td>
    <td><%= staff.age %></td>
    <td><%= staff.sex %></td>
    <td><%= staff.dob %></td>
    <td><%= staff.department.name %></td>
  </tr>
<% end %>
</table>

<br />

</div>

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2 class="label-warning"><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul class="nav">
      <% @department.errors.full_messages.each do |msg| %>
        <li class="label-info"><%= msg%></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<%= render "layouts/navigation"%>
<div class="modal modal-form " id="show">
<div class="modal-body">
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>
</div>
</div>

<div class="partial-overlay">
</div>

app/views/departments/index.html.erb
<%= render "layouts/navigation"%>
<div class="container">
<h1>Listing departments</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Staff Currently</th>
    <th></th>
    <th><i class="icon-wrench"></i>&nbsp;Action</th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td><%= department.staffs.count %></td>


    <td><i class="icon-th-large"></i>&nbsp<%= link_to 'Show', department %></td>

    <td><i class="icon-edit"></i>&nbsp;<%= link_to 'Edit', edit_department_path(department) %></td>
    <td><i class="icon-trash"></i>&nbsp;<%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Department', new_department_path, :class => "btn btn-primary" %>
<%= link_to 'Display all staffs', all_path, class: "pull-right" %>
<i class="icon-list pull-right"></i>

</div>

app/views/departments/new.html.erb
<div class="modal modal-form " id="show">
<div class="modal-body">
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>
</div>
</div>
<div class="partial-overlay">
</div>

app/views/departments/show.html.erb
<div class="modal modal-form"  id="show">
<div class="modal-body">

<p id="notice" class="label-success"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @department.name %>
</p>

<%=link_to "Display #{@department.name}'s staff", department_staffs_path(@department), class: "btn btn-primary" %>
<%= link_to 'Edit', edit_department_path(@department), class: "btn btn-warning" %> 
<%= link_to 'Back', departments_path, class: "btn" %>
</div>
</div>
<div class="partial-overlay">
</div>

app/views/home/index.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">

		<div class="container">
		<a href="#" class="brand">Nidalee company</a>
		<div class="nav-collapse">

			<ul class="nav">
				
				<% if signed_in?%>
				<li><%= link_to "Department", departments_path%></li>

				<%end%>
			</ul>
 
    		</div>
    		</div>
	</div>
</div>
<div class="banner">

<div class="container">
<div class="top"></div>
<h1>We always serve you</h1>
<h2>&emsp;&emsp;  a fancy cloth</h2>
<p>&emsp;&emsp;  You can find the new arrival cloth by </p>
<p>&emsp;&emsp;&emsp;&emsp;    just click the link below!! </p>

<a href="#" class="btn btn-large btn-primary">Visit official Website</a>
<%=link_to "Staff Login Here", departments_path, class: "btn btn-large btn-info"%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaffManagement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "css/bootstrap", :media => "all" %>
      <%= stylesheet_link_tag    "css/bootstrap-responsive", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/staffs/_form.html.erb
<%= simple_form_for([@department,@staff]) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="control-group">
  <div class="span3">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="span3">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="span3">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>
  <div class="span3">
    <%= f.label :sex %>
    <%= f.select :sex, [['Male'],['Female']] %>
  </div>
  <div class="span3">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>
    <div class="span3">
  <%=f.label :address%>
  <%=f.text_area :address%>
  </div>
  <div class="span7">
    <%= f.label :dob %>
    <%= f.date_select :dob, :start_year => 1940 %>
  </div>
  <div class="span3">
    <%= f.label :salary %>
    <%= f.text_field :salary %>
  </div>
  <div class="span3">
    <%= f.label :department %>
    <%= f.association :department, :label => false, :disabled => true %>
  </div>
  </div>
  <div class="span3">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/staffs/edit.html.erb
<%= render "layouts/navigation"%>


<div class="top"></div>
<div class="container">

<div class="span7 offset2">
<div class="span4">
<h2>Editing staff</h2>
</div>
<br><br><br>

<%= render 'form' %>


</div>

	<div class="span7 offset3">
	<br>
	<div class="span3">
	<%= link_to 'Show', [@department,@staff], class: "btn btn-success disabled " %> 
	
	<%= link_to 'Back', department_staffs_path, class: "btn disabled" %>
	</div>
	</div>
</div>

<div class="top"></div>

app/views/staffs/index.html.erb
<%= render "layouts/navigation"%>
<div class="container">
<h1>Listing staffs</h1>

<div class="control-group pull-right">
<%= form_tag department_staffs_path , :method => 'get' do %>
<%=text_field_tag :search, params[:search], id: "search", :placeholder => "Search Name "  %>
<%= submit_tag "search", :name => nil, class: "btn"%>
</div>
<% end %>


<table class="table">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Role</th>
    <th>Salary</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Dob</th>
     <th>Address</th>
    <th>Department</th>
    <th></th>
    <th><i class="icon-wrench"></i>&nbsp;Action</th>
    <th></th>
  </tr>

<% @staffs.each do |staff| %>
  <tr>
    <td><%= staff.first_name %></td>
    <td><%= staff.last_name %></td>
    <td><%= staff.role %></td>
     <td><%= staff.salary %></td>
    <td><%= staff.age %></td>
    <td><%= staff.sex %></td>
    <td><%= staff.dob %></td>
    <td><%= truncate(staff.address, :length => 15) %></td>
    <td><%= staff.department.name %></td>
    <td><i class="icon-th-large"></i>&nbsp;<%=link_to 'Show', [@department, staff]%></td>
    <td><i class="icon-edit"></i>&nbsp;<%= link_to 'Edit', edit_department_staff_path(staff.department, staff) %></td>
    <td><i class="icon-trash"></i>&nbsp;<%= link_to 'Destroy', [@department,staff], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>



</table>
<div class="text-center">
    
    <% if @staffs.empty?%>
    <div class="text-center alert"><em >NAME NOT FOUND </em></div>
<% end %>
</div>
<br />


<%= link_to 'New Staff', new_department_staff_path, :class => "btn btn-primary" %>
<div class="text-center">
<%= paginate @staffs%>
</div>


</div>
<div class="top"></div>

app/views/staffs/new.html.erb
<%= render "layouts/navigation"%>
<div class="container">
<div class="span7 offset3">
<h2>&emsp;New staff</h2>

<%= render 'form' %>


</div>
<div class="span7 offset3">
<br>
&emsp;&emsp;<%= link_to 'Back', department_staffs_path %>
</div>
</div>
<div class="top"></div>

app/views/staffs/show.html.erb
<div class="modal modal-form" id="show">
<div class="modal-body">
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @staff.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @staff.last_name %>
</p>

<p>
  <b>Age:</b>
  <%= @staff.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @staff.sex %>
</p>

<p>
  <b>Role:</b>
  <%= @staff.role %>
</p>
<p>
  <b>Address:</b>
  <%= @staff.address %>
</p>
<p>
  <b>Dob:</b>
  <%= @staff.dob %>
</p>

<p>
  <b>Salary:</b>
  <%= @staff.salary %>
</p>

<p>
  <b>Department:</b>
  <%= @staff.department.name %>
</p>


<%= link_to 'Edit', edit_department_staff_path(@department,@staff), class: "btn btn-success" %>
<%= link_to 'Back', department_staffs_path(@department), class: "btn" %>
</div>
</div>
<div class="partial-overlay">
</div>